version: '3'
services:
  go-metrics:
    container_name: gocd-metrics
    image: gocd-metrics:latest
    ports:
      - "9090:9090"
    links:
      - "mountebank"
    depends_on:
      - "mountebank"
    environment:
      GOCD_HOST: 'http://mountebank:4545'
  mountebank:
    container_name: mountebank
    image: jkris/mountebank:latest
    volumes:
    - .:/config
    ports:
    - 2525:2525
    - 4545:4545
    command: --configfile /config/mb.json --allowInjection
